repos:
  - repo: https://github.com/python-poetry/poetry
    rev: "1.7.0"
    hooks:
      - id: poetry-check
        args: [--directory=api]
      - id: poetry-lock
        args: [--directory=api]
      - id: poetry-install
        args: [--directory=api]
      - id: poetry-export
        args:
          [
            --directory=api,
            --without-hashes,
            -o,
            api/requirements.txt,
            -f,
            requirements.txt,
          ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: ^.*\.egg-info/
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
        exclude: tests/fixtures/invalid_lock/poetry\.lock
      - id: check-yaml
      - id: check-ast
      - id: debug-statements
      - id: check-docstring-first

  - repo: https://github.com/psf/black
    rev: 23.12.0
    hooks:
      - id: black
        language_version: python3.11
        args:
          [
            --line-length=88,
            --target-version=py311,
            --exclude=\.venv/,
            --exclude=\.nox/,
            --exclude=\.tox/,
            --exclude=\.eggs/,
            --exclude=build/,
            --exclude=dist/,
            --exclude=docs/,
            --exclude=\.mypy_cache/,
            --exclude=\.pytest_cache/,
            --exclude=\.git/,
            --exclude=\.github/,
            --exclude=\.vscode/,
            --exclude=\.pyright/,
            --exclude=\.pylint_cache/,
            --exclude=\.hypothesis/,
            --exclude=\.mypy/,
            --exclude=\.coverage/,
          ]

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: [--max-line-length=88, --ignore=E203]

  - repo: https://github.com/myint/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        args:
          [
            "--in-place",
            "--remove-all-unused-imports",
            "--remove-unused-variables",
            "--remove-duplicate-keys",
            ".",
          ]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--filter-files, --profile=black, --src-path=src, --gitignore]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.6
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@2.8.1

  - repo: https://github.com/pre-commit/pre-commit
    rev: v3.6.0
    hooks:
      - id: validate_manifest

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.8
    hooks:
      - id: ruff

  - repo: local
    hooks:
      - id: export-requirements
        name: Export requeriments.txt
        language: system
        pass_filenames: false
        entry: poetry export --without-hashes -o requirements.txt
        files: ^(pyproject\.toml|poetry\.lock)$
